import { useState } from 'react'

const FullName = () => {
  const [val, setVal] = useState('0')
  return (
    <div className='bg-slate-200 border-b-4 border-blue-400 inline-block p-4 mt-10 ml-20 rounded-2xl'>
      <div className='flex flex-col flex-1 gap-5'>
        <div className='flex gap-4 items-center'>
          <label className='text-black'>
            FirstName
          </label>
          <select className='bg-pink-500 text-white rounded-2xl p-2'>
            <option selected>Chọn họ</option>
            <option>Nguyễn</option>
            <option>Trần</option>
            <option>Lê</option>
            <option>Đỗ</option>
            <option>Đặng</option>
            <option>Thanh</option>
            <option>Thị</option>
            <option>Trung</option>
            <option>Hoàng</option>
            <option>Phạm</option>
            <option>Vũ</option>
            <option>Bùi</option>
            <option>Ngô</option>
            <option>Huỳnh</option>
            <option>Phan</option>
            <option>Võ</option>
            <option>Đào</option>
            <option>Hồ</option>
            <option>Trương</option>
            <option>Dương</option>
            <option>Lý</option>
            <option>Trịnh</option>
            <option>Kim</option>
            <option>Nguyễn</option>
            <option>Trần</option>
            <option>Lê</option>
            <option>Đỗ</option>
            <option>Đặng</option>
            <option>Thanh</option>
            <option>Thị</option>
            <option>Trung</option>
            <option>Đinh</option>
            <option>Phùng</option>
            <option>Đoàn</option>
            <option>Bành</option>
            <option>Quách</option>
            <option>Hoàng</option>
            <option>Ninh</option>
            <option>Nghiêm</option>
            <option>Mạc</option>
            <option>Châu</option>
            <option>Đồng</option>
            <option>Đổ</option>
            <option>Tạ</option>
            <option>Tô</option>
            <option>Lỗ</option>
            <option>Quang</option>
            <option>Ngân</option>
            <option>Quỳnh</option>
            <option>Kiều</option>
            <option>Hoài</option>
            <option>Quốc</option>
            <option>Thành</option>
            <option>Minh</option>
            <option>Sơn</option>
            <option>Phú</option>
            <option>Hà</option>
            <option>Cao</option>
            <option>Nguyễn</option>
            <option>Trần</option>
            <option>Lê</option>
            <option>Đỗ</option>
            <option>Đặng</option>
            <option>Thanh</option>
            <option>Thị</option>
            <option>Ttrung</option>
            <option>Hoàng</option>
            <option>Phạm</option>
            <option>Vũ</option>
            <option>Bùi</option>
            <option>Ngô</option>
            <option>Huỳnh</option>
            <option>Phan</option>
            <option>Võ</option>
            <option>Đào</option>
            <option>Hồ</option>
            <option>Trương</option>
            <option>Dương</option>
            <option>Lý</option>
            <option>Trịnh</option>
            <option>Kim</option>
            <option>Nguyễn</option>
            <option>Trần</option>
            <option>Lê</option>
            <option>Đỗ</option>
            <option>Đặng</option>
            <option>Thanh</option>
            <option>Thị</option>
            <option>Trung</option>
            <option>Đinh</option>
            <option>Phùng</option>
            <option>Đoàn</option>
            <option>Bành</option>
            <option>Quách</option>
            <option>Hoàng</option>
            <option>Ninh</option>
            <option>Nghiêm</option>
            <option>Mạc</option>
            <option>Châu</option>
            <option>Đồng</option>
            <option>Đổ</option>
            <option>Tạ</option>
            <option>Tô</option>
            <option>Lỗ</option>
            <option>Quang</option>
            <option>Ngân</option>
            <option>Quỳnh</option>
            <option>Kiều</option>
            <option>Hoài</option>
            <option>Quốc</option>
            <option>Thành</option>
            <option>Minh</option>
            <option>Sơn</option>
            <option>Phú</option>
            <option>Hà</option>
            <option>Cao</option>
            <option>Nguyễn</option>
            <option>Trần</option>
            <option>Lê</option>
            <option>Đỗ</option>
            <option>Đặng</option>
            <option>Thanh</option>
            <option>Thị</option>
            <option>Ttrung</option>
            <option>Hoàng</option>
            <option>Phạm</option>
            <option>Vũ</option>
            <option>Bùi</option>
            <option>Ngô</option>
            <option>Huỳnh</option>
            <option>Phan</option>
            <option>Võ</option>
            <option>Đào</option>
            <option>Hồ</option>
            <option>Trương</option>
            <option>Dương</option>
            <option>Lý</option>
            <option>Trịnh</option>
            <option>Kim</option>
            <option>Nguyễn</option>
            <option>Trần</option>
            <option>Lê</option>
            <option>Đỗ</option>
            <option>Đặng</option>
            <option>Thanh</option>
            <option>Thị</option>
            <option>Trung</option>
            <option>Đinh</option>
            <option>Phùng</option>
            <option>Đoàn</option>
            <option>Bành</option>
            <option>Quách</option>
            <option>Hoàng</option>
            <option>Ninh</option>
            <option>Nghiêm</option>
            <option>Mạc</option>
            <option>Châu</option>
            <option>Đồng</option>
            <option>Đổ</option>
            <option>Tạ</option>
            <option>Tô</option>
            <option>Lỗ</option>
            <option>Quang</option>
            <option>Ngân</option>
            <option>Quỳnh</option>
            <option>Kiều</option>
            <option>Hoài</option>
            <option>Quốc</option>
            <option>Thành</option>
            <option>Minh</option>
            <option>Sơn</option>
            <option>Phú</option>
            <option>Hà</option>
            <option>Cao</option>
            <option>Nguyễn</option>
            <option>Trần</option>
            <option>Lê</option>
            <option>Đỗ</option>
            <option>Đặng</option>
            <option>Thanh</option>
            <option>Thị</option>
            <option>Trung</option>
            <option>Hoàng</option>
            <option>Phạm</option>
            <option>Vũ</option>
            <option>Bùi</option>
            <option>Ngô</option>
            <option>Huỳnh</option>
            <option>Phan</option>
            <option>Võ</option>
            <option>Đào</option>
            <option>Hồ</option>
            <option>Trương</option>
            <option>Dương</option>
            <option>Lý</option>
            <option>Trịnh</option>
            <option>Kim</option>
            <option>Nguyễn</option>
            <option>Trần</option>
            <option>Lê</option>
            <option>Đỗ</option>
            <option>Đặng</option>
            <option>Thanh</option>
            <option>Thị</option>
            <option>Trung</option>
            <option>Đinh</option>
            <option>Phùng</option>
            <option>Đoàn</option>
            <option>Bành</option>
            <option>Quách</option>
            <option>Hoàng</option>
            <option>Ninh</option>
            <option>Nghiêm</option>
            <option>Mạc</option>
            <option>Châu</option>
            <option>Đồng</option>
            <option>Đổ</option>
            <option>Tạ</option>
            <option>Tô</option>
            <option>Lỗ</option>
            <option>Quang</option>
            <option>Ngân</option>
            <option>Quỳnh</option>
            <option>Kiều</option>
            <option>Hoài</option>
            <option>Quốc</option>
            <option>Thành</option>
            <option>Minh</option>
            <option>Sơn</option>
            <option>Phú</option>
            <option>Hà</option>
          </select>
        </div>

        <div className='flex gap-4 items-center'>
          <label className='text-black'>
            LastName
          </label>
          <select className='bg-blue-500 text-white rounded-2xl p-2'>
            <option selected>Chọn tên</option>
            <option>An</option>
            <option>Linh</option>
            <option>Phúc</option>
            <option>Duy</option>
            <option>Lam</option>
            <option>Liễu</option>
            <option>Bích</option>
            <option>Bữu</option>
            <option>Ngọc</option>
            <option>Thiện</option>
            <option>Ánh</option>
            <option>Anh</option>
            <option>Chí</option>
            <option>Bảo</option>
            <option>Thúy</option>
            <option>Thu</option>
            <option>Hạnh</option>
            <option>Dương</option>
            <option>Ngân</option>
            <option>Nhân</option>
            <option>Quốc</option>
            <option>Nhật</option>
            <option>Khánh</option>
            <option>Quân</option>
            <option>Tâm</option>
            <option>Hùng</option>
            <option>Quang</option>
            <option>Đạt</option>
            <option>Đức</option>
            <option>Hiếu</option>
            <option>Phong</option>
            <option>Quyền</option>
            <option>Trí</option>
            <option>Tuấn</option>
            <option>Việt</option>
            <option>Sơn</option>
            <option>Hải</option>
            <option>Thắng</option>
            <option>Thành</option>
            <option>Duy</option>
            <option>Long</option>
            <option>Phúc</option>
            <option>Hòa</option>
            <option>Minh</option>
            <option>Quyết</option>
            <option>Minh</option>
            <option>Hoài</option>
            <option>Phương</option>
            <option>Nga</option>
            <option>Thanh</option>
            <option>Trang</option>
            <option>Tuyết</option>
            <option>Yến</option>
            <option>Thuận</option>
            <option>Như</option>
            <option>Hoàng</option>
            <option>An</option>
            <option>Nhật</option>
            <option>Ngọc</option>
            <option>Quỳnh</option>
            <option>Thủy</option>
            <option>Diệu</option>
            <option>Phương</option>
            <option>Đan</option>
            <option>Hương</option>
            <option>Thơ</option>
            <option>Ngọc</option>
            <option>Trâm</option>
            <option>Thu</option>
            <option>Hà</option>
            <option>Ly</option>
            <option>Linh</option>
            <option>Thi</option>
            <option>Phượng</option>
            <option>My</option>
            <option>Hoàng</option>
            <option>Thúy</option>
            <option>Thiệu</option>
            <option>Anh</option>
            <option>Phương</option>
            <option>Ngọc</option>
            <option>Bích</option>
            <option>Thu</option>
            <option>Trúc</option>
            <option>Thi</option>
            <option>Hà</option>
            <option>Ngân</option>
            <option>Anh</option>
            <option>Thảo</option>
            <option>Phúc</option>
            <option>Minh</option>
            <option>Hồng</option>
            <option>Trang</option>
            <option>Quỳnh</option>
            <option>Đức</option>
            <option>Thịnh</option>
            <option>Thái</option>
            <option>Thanh</option>
            <option>Đình</option>
            <option>Khải</option>
            <option>Hoàng</option>
            <option>Thịnh</option>
            <option>Tuấn</option>
            <option>Điệp</option>
            <option>Đông</option>
            <option>Quỳnh</option>
            <option>Anh</option>
            <option>Thi</option>
            <option>Sang</option>
            <option>An</option>
            <option>Linh</option>
            <option>Phúc</option>
            <option>Duy</option>
            <option>Lam</option>
            <option>Liễu</option>
            <option>Bích</option>
            <option>Bữu</option>
            <option>Ngọc</option>
            <option>Thiện</option>
            <option>Ánh</option>
            <option>Anh</option>
            <option>Chí</option>
            <option>Bảo</option>
            <option>Thúy</option>
            <option>Thu</option>
            <option>Hạnh</option>
            <option>Dương</option>
            <option>Ngân</option>
            <option>Nhân</option>
            <option>Quốc</option>
            <option>Nhật</option>
            <option>Khánh</option>
            <option>Quân</option>
            <option>Tâm</option>
            <option>Hùng</option>
            <option>Quang</option>
            <option>Đạt</option>
            <option>Đức</option>
            <option>Hiếu</option>
            <option>Phong</option>
            <option>Quyền</option>
            <option>Trí</option>
            <option>Tuấn</option>
            <option>Việt</option>
            <option>Sơn</option>
            <option>Hải</option>
            <option>Thắng</option>
            <option>Thành</option>
            <option>Duy</option>
            <option>Long</option>
            <option>Phúc</option>
            <option>Hòa</option>
            <option>Minh</option>
            <option>Quyết</option>
            <option>Minh</option>
            <option>Hoài</option>
            <option>Phương</option>
            <option>Nga</option>
            <option>Thanh</option>
            <option>Trang</option>
            <option>Tuyết</option>
            <option>Yến</option>
            <option>Thuận</option>
            <option>Như</option>
            <option>Hoàng</option>
            <option>An</option>
            <option>Nhật</option>
            <option>Ngọc</option>
            <option>Quỳnh</option>
            <option>Thủy</option>
            <option>Diệu</option>
            <option>Phương</option>
            <option>Đan</option>
            <option>Hương</option>
            <option>Thơ</option>
            <option>Ngọc</option>
            <option>Trâm</option>
            <option>Thu</option>
            <option>Hà</option>
            <option>Ly</option>
            <option>Linh</option>
            <option>Thi</option>
            <option>Phượng</option>
            <option>My</option>
            <option>Hoàng</option>
            <option>Thúy</option>
            <option>Thiệu</option>
            <option>Anh</option>
            <option>Phương</option>
            <option>Ngọc</option>
            <option>Bích</option>
            <option>Thu</option>
            <option>Trúc</option>
            <option>Thi</option>
            <option>Hà</option>
            <option>Ngân</option>
            <option>Anh</option>
            <option>Thảo</option>
            <option>Phúc</option>
            <option>Minh</option>
            <option>Hồng</option>
            <option>Trang</option>
            <option>Quỳnh</option>
            <option>Đức</option>
            <option>Thịnh</option>
            <option>Thái</option>
            <option>Thanh</option>
            <option>Đình</option>
            <option>Khải</option>
            <option>Hoàng</option>
            <option>Thịnh</option>
            <option>Tuấn</option>
            <option>Điệp</option>
            <option>Đông</option>
            <option>Quỳnh</option>
            <option>Anh</option>
            <option>Thi</option>
            <option>Sang</option>
            <option>An</option>
            <option>Linh</option>
            <option>Phúc</option>
            <option>Duy</option>
            <option>Lam</option>
            <option>Liễu</option>
            <option>Bích</option>
            <option>Bữu</option>
            <option>Ngọc</option>
            <option>Thiện</option>
            <option>Ánh</option>
            <option>Anh</option>
            <option>Chí</option>
            <option>Bảo</option>
            <option>Thúy</option>
            <option>Thu</option>
            <option>Hạnh</option>
            <option>Dương</option>
            <option>Ngân</option>
            <option>Nhân</option>
            <option>Quốc</option>
            <option>Nhật</option>
            <option>Khánh</option>
            <option>Quân</option>
            <option>Tâm</option>
            <option>Hùng</option>
            <option>Quang</option>
            <option>Đạt</option>
            <option>Đức</option>
            <option>Hiếu</option>
            <option>Phong</option>
            <option>Quyền</option>
            <option>Trí</option>
            <option>Tuấn</option>
            <option>Việt</option>
            <option>Sơn</option>
            <option>Hải</option>
            <option>Thắng</option>
            <option>Thành</option>
            <option>Duy</option>
            <option>Long</option>
            <option>Phúc</option>
            <option>Hòa</option>
            <option>Minh</option>
            <option>Quyết</option>
            <option>Minh</option>
            <option>Hoài</option>
            <option>Phương</option>
            <option>Nga</option>
            <option>Thanh</option>
            <option>Trang</option>
            <option>Tuyết</option>
            <option>Yến</option>
            <option>Thuận</option>
            <option>Như</option>
            <option>Hoàng</option>
            <option>An</option>
            <option>Nhật</option>
            <option>Ngọc</option>
            <option>Quỳnh</option>
            <option>Thủy</option>
            <option>Diệu</option>
            <option>Phương</option>
            <option>Đan</option>
            <option>Hương</option>
            <option>Thơ</option>
            <option>Ngọc</option>
            <option>Trâm</option>
            <option>Thu</option>
            <option>Hà</option>
            <option>Ly</option>
            <option>Linh</option>
            <option>Thi</option>
            <option>Phượng</option>
            <option>My</option>
            <option>Hoàng</option>
            <option>Thúy</option>
            <option>Thiệu</option>
            <option>Anh</option>
            <option>Phương</option>
            <option>Ngọc</option>
            <option>Bích</option>
            <option>Thu</option>
            <option>Trúc</option>
            <option>Thi</option>
            <option>Hà</option>
            <option>Ngân</option>
            <option>Anh</option>
            <option>Thảo</option>
            <option>Phúc</option>
            <option>Minh</option>
            <option>Hồng</option>
            <option>Trang</option>
            <option>Quỳnh</option>
            <option>Đức</option>
            <option>Thịnh</option>
            <option>Thái</option>
            <option>Thanh</option>
            <option>Đình</option>
            <option>Khải</option>
            <option>Hoàng</option>
            <option>Thịnh</option>
            <option>Tuấn</option>
            <option>Điệp</option>
            <option>Đông</option>
            <option>Quỳnh</option>
            <option>Anh</option>
            <option>Thi</option>
            <option>Sang</option>
            <option>An</option>
            <option>Linh</option>
            <option>Phúc</option>
            <option>Duy</option>
            <option>Lam</option>
            <option>Liễu</option>
            <option>Bích</option>
            <option>Bữu</option>
            <option>Ngọc</option>
            <option>Thiện</option>
            <option>Ánh</option>
            <option>Anh</option>
            <option>Chí</option>
            <option>Bảo</option>
            <option>Thúy</option>
            <option>Thu</option>
            <option>Hạnh</option>
            <option>Dương</option>
            <option>Ngân</option>
            <option>Nhân</option>
            <option>Quốc</option>
            <option>Nhật</option>
            <option>Khánh</option>
            <option>Quân</option>
            <option>Tâm</option>
            <option>Hùng</option>
            <option>Quang</option>
            <option>Đạt</option>
            <option>Đức</option>
            <option>Hiếu</option>
            <option>Phong</option>
            <option>Quyền</option>
            <option>Trí</option>
            <option>Tuấn</option>
            <option>Việt</option>
            <option>Sơn</option>
            <option>Hải</option>
            <option>Thắng</option>
            <option>Thành</option>
            <option>Duy</option>
            <option>Long</option>
            <option>Phúc</option>
            <option>Hòa</option>
            <option>Minh</option>
            <option>Quyết</option>
            <option>Minh</option>
            <option>Hoài</option>
            <option>Phương</option>
            <option>Nga</option>
            <option>Thanh</option>
            <option>Trang</option>
            <option>Tuyết</option>
            <option>Yến</option>
            <option>Thuận</option>
            <option>Như</option>
            <option>Hoàng</option>
            <option>An</option>
            <option>Nhật</option>
            <option>Ngọc</option>
            <option>Quỳnh</option>
            <option>Thủy</option>
            <option>Diệu</option>
            <option>Phương</option>
            <option>Đan</option>
            <option>Hương</option>
            <option>Thơ</option>
            <option>Ngọc</option>
            <option>Trâm</option>
            <option>Thu</option>
            <option>Hà</option>
            <option>Ly</option>
            <option>Linh</option>
            <option>Thi</option>
            <option>Phượng</option>
            <option>My</option>
            <option>Hoàng</option>
            <option>Thúy</option>
            <option>Thiệu</option>
            <option>Anh</option>
            <option>Phương</option>
            <option>Ngọc</option>
            <option>Bích</option>
            <option>Thu</option>
            <option>Trúc</option>
            <option>Thi</option>
            <option>Hà</option>
            <option>Ngân</option>
            <option>Anh</option>
            <option>Thảo</option>
            <option>Phúc</option>
            <option>Minh</option>
            <option>Hồng</option>
            <option>Trang</option>
            <option>Quỳnh</option>
            <option>Đức</option>
            <option>Thịnh</option>
            <option>Thái</option>
            <option>Thanh</option>
            <option>Đình</option>
            <option>Khải</option>
            <option>Hoàng</option>
            <option>Thịnh</option>
            <option>Tuấn</option>
            <option>Điệp</option>
            <option>Đông</option>
            <option>Quỳnh</option>
            <option>Anh</option>
            <option>Thi</option>
            <option>Sang</option>
            <option>An</option>
            <option>Linh</option>
            <option>Phúc</option>
            <option>Duy</option>
            <option>Lam</option>
            <option>Liễu</option>
            <option>Bích</option>
            <option>Bữu</option>
            <option>Ngọc</option>
            <option>Thiện</option>
            <option>Ánh</option>
            <option>Anh</option>
            <option>Chí</option>
            <option>Bảo</option>
            <option>Thúy</option>
            <option>Thu</option>
            <option>Hạnh</option>
            <option>Dương</option>
            <option>Ngân</option>
            <option>Nhân</option>
            <option>Quốc</option>
            <option>Nhật</option>
            <option>Khánh</option>
            <option>Quân</option>
            <option>Tâm</option>
            <option>Hùng</option>
            <option>Quang</option>
            <option>Đạt</option>
            <option>Đức</option>
            <option>Hiếu</option>
            <option>Phong</option>
            <option>Quyền</option>
            <option>Trí</option>
            <option>Tuấn</option>
            <option>Việt</option>
            <option>Sơn</option>
            <option>Hải</option>
            <option>Thắng</option>
            <option>Thành</option>
            <option>Duy</option>
            <option>Long</option>
            <option>Phúc</option>
            <option>Hòa</option>
            <option>Minh</option>
            <option>Quyết</option>
            <option>Minh</option>
            <option>Hoài</option>
            <option>Phương</option>
            <option>Nga</option>
            <option>Thanh</option>
            <option>Trang</option>
            <option>Tuyết</option>
            <option>Yến</option>
            <option>Thuận</option>
            <option>Như</option>
            <option>Hoàng</option>
            <option>An</option>
            <option>Nhật</option>
            <option>Ngọc</option>
            <option>Quỳnh</option>
            <option>Thủy</option>
            <option>Diệu</option>
            <option>Phương</option>
            <option>Đan</option>
            <option>Hương</option>
            <option>Thơ</option>
            <option>Ngọc</option>
            <option>Trâm</option>
            <option>Thu</option>
            <option>Hà</option>
            <option>Ly</option>
            <option>Linh</option>
            <option>Thi</option>
            <option>Phượng</option>
            <option>My</option>
            <option>Hoàng</option>
            <option>Thúy</option>
            <option>Thiệu</option>
            <option>Anh</option>
            <option>Phương</option>
            <option>Ngọc</option>
            <option>Bích</option>
            <option>Thu</option>
            <option>Trúc</option>
            <option>Thi</option>
            <option>Hà</option>
            <option>Ngân</option>
            <option>Anh</option>
            <option>Thảo</option>
            <option>Phúc</option>
            <option>Minh</option>
            <option>Hồng</option>
            <option>Trang</option>
            <option>Quỳnh</option>
            <option>Đức</option>
            <option>Thịnh</option>
            <option>Thái</option>
            <option>Thanh</option>
            <option>Đình</option>
            <option>Khải</option>
            <option>Hoàng</option>
            <option>Thịnh</option>
            <option>Tuấn</option>
            <option>Điệp</option>
            <option>Đông</option>
            <option>Quỳnh</option>
            <option>Anh</option>
            <option>Thi</option>
          </select>
        </div>

        <div>
          <div className='text-black flex flex-col'>
            <h2>Số CCCD</h2>
            <input
              onChange={(e) => {
                setVal(e.target.value)
              }}
              type='range'
              min={'000000000000'}
              max={'999999999999'}
            />
            <h1 className='text-2xl text-center '>
              {new Array(
                12 - parseInt(val.length)
              )
                .fill(0)
                .join('')}
              {val}
            </h1>
          </div>
        </div>
      </div>
    </div>
  )
}

export default FullName
